spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: reportsapi
    password: 12345
    url: jdbc:mysql://localhost:3306/reportsapi
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  
      
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        
        
  mvc:
    pathmatch:
      matching-strategy: 'ANT_PATH_MATCHER'